name: Chromatic Compare Branches

on:
  workflow_dispatch:
    inputs:
      base-branch:
        description: "Base branch to compare"
        required: true
        default: "main"
      head-branch:
        description: "Head branch to compare"
        required: true

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Run Chromatic comparison
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        run: |
          pnpm dlx chromatic --patch-build ${{ github.event.inputs.head-branch }}...${{ github.event.inputs.base-branch }}
